#!/bin/sh

vol=$(amixer get Master|grep -oE '[0-9]{1,3}%'|sed ':a; N; $!ba; s/\n/ /g'|awk '{printf "%.0f", (($1+$2)/2)}')

if [[ $vol == 100 ]]; then
  volicon="📢"
elif [[ $vol > 62 ]]; then
  volicon="🔊"
elif [[ $vol > 40 ]]; then
  volicon="🔉"
elif [[ $vol > 0 ]]; then
  volicon="🔈"
else
  volicon="🔇"
fi

printf "%s%.0f%%" "${volicon}" "${vol}"
