#!/usr/bin/python
# -*- coding: utf-8 -*-

import re
import utils

speakers = []
cmd = "amixer get Master"

amixer = utils.popen(cmd).strip()
amixer = [x.strip() for x in amixer.split("\n")]
for line in amixer:
    m = re.match(r".*\[([0-9]{1,3})%\].*", line)
    if m:
        speakers.append(int(m.group(1)))

speakers_avg = sum(speakers) / len(speakers)

if speakers_avg == 100:
    icon = "📢"
elif speakers_avg > 60:
    icon = "🔊"
elif speakers_avg > 30:
    icon = "🔉"
elif speakers_avg > 0:
    icon = "🔈"
else:
    icon = "🔇"

res = "{}{:2.0f}%".format(icon, speakers_avg)

print(res)
