#!/usr/bin/python
# -*- coding: utf-8 -*-

import utils

icons = {
    "vim": "",
    # "msedge": "󰌀",
    # "chrome": "",
    "ncmpcpp": "󰝚",
    "netease-cloud-music": "󰝚",
    "ffmpeg": "",
    "clash": "🐬",
}

apps = icons.keys()

iconslist = [x for x in [icons.get(app, "") for app in apps if utils.in_running(app)] if x]

res = "  ".join(iconslist)

print(res, end="|")
