#!/usr/bin/python
# -*- coding: utf-8 -*-

import re
import utils

lr = []
cmd = "amixer get Capture"

amixer = utils.popen(cmd).strip()
amixer = [x.strip() for x in amixer.split("\n")]
for line in amixer:
    m = re.match(r".*\[([0-9]{1,3})%\].*", line)
    if m:
        lr.append(int(m.group(1)))

avg = sum(lr) / len(lr)

if avg == 100:
    icon = "🔬"
elif avg > 60:
    icon = ""
elif avg > 30:
    icon = "󰍬"
elif avg > 0:
    icon = "󰍮"
else:
    icon = ""

res = "{}{:2.0f}".format(icon, avg)

print(res)
