#!/usr/bin/python
# -*- coding: utf-8 -*-

import time
import utils
import numpy as np

STAT_PATH = "/proc/stat"

icons = {
    0: "▁",
    1: "▂",
    2: "▃",
    3: "▄",
    4: "▅",
    5: "▆",
    6: "▇",
    7: "█",
    8: "█",
}

stat1 = [[int(y) for y in x[3:].split()] for x in utils.read_file(STAT_PATH).strip().split("\n")
         if x.startswith("cpu") and x[3] != " "]

time.sleep(0.1)
stat2 = [[int(y) for y in x[3:].split()] for x in utils.read_file(STAT_PATH).strip().split("\n")
         if x.startswith("cpu") and x[3] != " "]

delta = np.array([(sum(stat2[i][1:3]) - sum(stat1[i][1:3])) for i in range(len(stat1))])
min, max = delta.min(), delta.max()
delta = [int(x) for x in np.floor(8 * (delta / (max - min) if (max - min) else delta))]

res = "".join([icons.get(i, "▁") for i in delta])

print(res)
